#!/usr/bin/env bash
# add new path to the path {{{
function addpath {
    # $1: directory to be added
    local p
    eval p="$1"
    if [[ "$PATH" != *"$p"* ]]; then
        PATH="$p":"$PATH"
        echo "adding path: $p"
    fi
}
# }}}

# back n level directory {{{
function up..() {
    # $1: number of parent folders
    local n=${1:-1}
    local DEST=${PWD}
    for ((; n != 0; n--)); do
         DEST=$(dirname $DEST)
    done 
    cd $DEST
}
# }}}

# sum {{{
function totalsum()
{
    # http://stackoverflow.com/questions/450799/shell-command-to-sum-integers-one-per-line
    paste -s -d+ - | bc
}
# }}}

# fdr - cd to selected parent directory
fdr() {
  local declare dirs=()
  start_path=$(pwd)
  while [[ "$start_path" != '/' ]]; do
      if [[ -d "$start_path" ]]; then
          dirs+=("$start_path")
      fi
      start_path=$(dirname "$start_path")
  done

  DIR=$(echo ${dirs[@]} | tr ' ' '\n' | fzf-tmux --tac)
  cd "$DIR"
}

# vim: fdm=marker
