#!/usr/bin/env bash

# order matters
_PATHS=(
    ###### user
    "$HOME/bin"
    "$HOME/.local/bin"
    ###### 3rd party
    "$HOME/.anyenv/bin"
    "$HOME/.pyenv/bin"
    ###### system default
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
)
export PATH=$(IFS=':'; echo "${_PATHS[*]}")
