#!/usr/bin/env bash
# enable golang {{{
if (( ${ENABLE_GO_GVM} )); then
    GVM_HOME="$HOME/.gvm"
    GVM_MAIN="$GVM_HOME/scripts/gvm-default"
    export GVM_ROOT="$GVM_HOME"
    export GO15VENDOREXPERIMENT=1
    [[ -s "$GVM_MAIN" ]] && source "$GVM_MAIN"
fi #}}}
# enalbe ruby {{{
if (( ${ENABLE_RUBY_RVM} )); then
    RVM_HOME="$HOME/.rvm"
    RVM_MAIN="$HOME/.rvm/scripts/rvm"
    [[ -s "$RVM_MAIN" ]] && source "$RVM_MAIN"
fi #}}}
# enable scm breeze {{{
if (( ${ENABLE_SCM_BREEZE} )); then
    SCM_HOME="$HOME/.scm_breeze"
    SCM_MAIN="$SCM_HOME/scm_breeze.sh"
    [[ -s "$SCM_MAIN" ]] && source "$SCM_MAIN"
fi #}}}
# enable scmpuff {{{
if (( ${ENABLE_SCMPUFF} )); then
    if hash scmpuff 2>/dev/null; then
        eval "$(scmpuff init -s)"
    fi
fi #}}}
# enable scmpuff {{{
if (( ${ENABLE_TMUXINATOR} )); then
    TMUXINATOR_HOME="$HOME/.tmuxinator"
    TMUXINATOR_MAIN="$HOME/.tmuxinator/scripts/tmuxinator"
    [[ -s "$TMUXINATOR_MAIN" ]] && source "$TMUXINATOR_MAIN"
fi #}}}

export ZPLUG_HOME=/usr/local/opt/zplug

# vim: fdm=marker
