#!/usr/bin/env bash
# enalbe ruby {{{
if (( ${ENABLE_RUBY_RVM} )); then
    RVM_HOME="$HOME/.rvm"
    RVM_MAIN="$HOME/.rvm/scripts/rvm"
    [[ -s "$RVM_MAIN" ]] && source "$RVM_MAIN"
fi #}}}
# enable scm breeze {{{
if (( ${ENABLE_SCM_BREEZE} )); then
    SCM_HOME="$HOME/.scm_breeze"
    SCM_MAIN="$SCM_HOME/scm_breeze.sh"
    [[ -s "$SCM_MAIN" ]] && source "$SCM_MAIN"
fi #}}}
# enable scmpuff {{{
if (( ${ENABLE_SCMPUFF} )); then
    if hash scmpuff 2>/dev/null; then
        eval "$(scmpuff init -s)"
    fi
fi #}}}
# enable scmpuff {{{
if (( ${ENABLE_TMUXINATOR} )); then
    TMUXINATOR_HOME="$HOME/.tmuxinator"
    TMUXINATOR_MAIN="$HOME/.tmuxinator/scripts/tmuxinator"
    [[ -s "$TMUXINATOR_MAIN" ]] && source "$TMUXINATOR_MAIN"
fi #}}}

case $OSTYPE in
    *darwin*)
        export ZPLUG_HOME=/usr/local/opt/zplug
        ;;
    *)
        export ZPLUG_HOME=~/.zplug
        ;;
esac

export ZPLUG_REPOS=~/.zplug/repos
export ZPLUG_BIN=~/.zplug/bin
# vim: fdm=marker
