alias j12='export JAVA_HOME=`/usr/libexec/java_home -v 12`; java -version'
alias j11='export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version'
alias j10='export JAVA_HOME=`/usr/libexec/java_home -v 10`; java -version'
alias j9='export JAVA_HOME=`/usr/libexec/java_home -v 9`; java -version'
alias j8='export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version'
alias j7='export JAVA_HOME=`/usr/libexec/java_home -v 1.7`; java -version'
