if [[ `uname` != "Darwin" ]]; then
    return
fi

path=(
    "$HOME/Library/Application Support/waveterm/bin"
    "/opt/homebrew/opt/avr-gcc@8/bin/"
    "/Applications/Ghostty.app/Contents/MacOS"
    "/Applications/flameshot.app/Contents/MacOS"
    "/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin"
    "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
    $path
)