#+title: Readme
* Table of content :TOC:
- [[#application][Application]]
- [[#custom-configs][Custom configs]]
  - [[#input-methods][Input methods]]
  - [[#archive][Archive]]
  - [[#helpful-documents][Helpful documents]]
  - [[#helpful-discussion][Helpful discussion]]
- [[#gnu-stow][Gnu stow]]
  - [[#macos][MacOS]]
  - [[#linux][Linux]]
- [[#tagging][Tagging]]

* Application

Use [[https://github.com/rime/plum][東風破]] to install other input methods.

* Custom configs
:PROPERTIES:
:header-args: :mkdirp yes
:END:

#+NAME: variables
| Variable | Value   | Description           |
|----------+---------+-----------------------|
| basedir  | .build/ | dotfile target folder |

** Input methods
*** 注音 (bopomofo_tw)
*** 小鶴雙拼注音
Modify too many parts, so create 3 versions.
**** flypy_luna
The base version.

使用朙月拼音字碼表

**** flypy_self

使用自己轉換的字碼表
Python's regex module works very differently with rime's regex pattern, I made some changes to cope with it, I haven't found any mistakes yet, we will see.

**** flypy_quick5
雙拼有音形方案，但形是用簡體字，官方也只給出 binary 檔案，不給完整碼表。
[[https://github.com/functoreality/rime-flypy-zrmfast/tree/master][rime-flypy-zrmfast]] 給出了一個類似的簡體方案。

想起了速成也是用兩碼，兩個加在一起好像很可以，有多了一個理由學倉頡了。

[[https://github.com/JACKCHAN000/Rime-Quick5-Setup/tree/main][rime quick5]], 速成現成的字碼表，不然就要自己如 [[https://github.com/rime/rime-quick/blob/3fe5911ba608cb2df1b6301b76ad1573bd482a76/quick5.schema.yaml#L56][Rime 官方速成]] 取頭取尾。

**** Limitations
I would like to enable ~spelling_hints~ for phrase reverse lookup, but it is not support yet, only the first character will apply the filter rules. [[https://github.com/rime/home/issues/298][issue]]

*** array30

https://github.com/rime/rime-array
I really like the rules but like many people has said, it is not ergonomic, use pinky fingers quite often and some common characters have to tap with the same finger multiple times in the same column.

*** 大新倉頡 (newcj)
https://github.com/Joey-Li/Newcj_rime

*** 嘸蝦米 (liur)
https://github.com/hsuanyi-chou/rime-liur

** Archive
*** Dvorak mapping
I'm sick of having dealing with different keyboard layouts everytime I install a new application.
these are settings I used for bopomofo in dvorak layout

#+begin_src yaml
patch:
  schema/name: bopomofo (dvorak)
  speller/alphabet: "1'a;2,oq.ejpuk5yixfdbghm8ctw9rnv0lsz[ 6347"
  speller/initials: "1'a;2,oq.ejpuk5yixfdbghm8ctw9rnv0lsz["
  speller/algebra/@last: "xlit|bpmfdtnlgkhjqxZCSrzcsiuvaoeEAIOUMNKGR12345|1'a;2,oq.ejpuk5yixfdbghm8ctw9rnv0lsz[ 6347|"
  translator/preedit_format/@0: "xlit|1'a;2,oq.ejpuk5yixfdbghm8ctw9rnv0lsz[ 6347'|ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦˉˊˇˋ˙ |"
  all_bpm/preedit_format/@0: "xlit|1'a;2,oq.ejpuk5yixfdbghm8ctw9rnv0lsz[ 6347'|ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦˉˊˇˋ˙ |"
  menu/alternative_select_keys: "UHETON"
#+end_src
** Helpful documents
[[https://github.com/rime/home/wiki/RimeWithSchemata][Basic guide]]
[[https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md][Schema.yaml definition]]
[[https://github.com/rime/home/wiki/Configuration][How to write patch file]]
[[https://github.com/rime/home/wiki][wiki]]
[[https://www.educative.io/blog/advanced-yaml-syntax-cheatsheet][Anchor and alias in yaml]]
[[https://github.com/Ponpon55837/Squirrel/tree/master][squirrel styling]]

** Helpful discussion
[[https://github.com/rime/squirrel/issues/607#issuecomment-995045505][issue 607]], encode_commit_history, max_phrase_length, enable_encoder
[[https://github.com/rime/home/issues/9#issuecomment-528171971][issue 9]], workaround for allowing user phrases and fixed position of words using 2 translator with different ~initial_quality~

* Gnu stow
#+begin_src pattern :tangle .stow-local-ignore
#+end_src

** MacOS

Install dotfile
#+begin_src sh :results silent
stow -v1 -t ~/Library/Rime .build
stow -v1 -t ~/Library/Rime assets
#+end_src

Uninstall dotfile
#+begin_src sh :results silent
stow -t ~/Library/Rime -D .build
stow -t ~/Library/Rime -D assets
#+end_src

** Linux
*** ibus

Install dotfile
#+begin_src sh :results silent
stow -v1 -t ~/.config/ibus/rime .build
stow -v1 -t ~/.config/ibus/rime assets
#+end_src

Uninstall dotfile
#+begin_src sh :results silent
stow -t ~/.config/ibus/rime -D .build
stow -t ~/.config/ibus/rime -D assets
#+end_src

*** fcitx

Install dotfile
#+begin_src sh :results silent
stow -v1 -t ~/.local/share/fcitx5/rime .build
stow -v1 -t ~/.local/share/fcitx5/rime assets
#+end_src

Uninstall dotfile
#+begin_src sh :results silent
stow -t ~/.local/share/fcitx5/rime -D .build
stow -t ~/.local/share/fcitx5/rime -D assets
#+end_src

* Tagging
#+begin_src tag :tangle TAGS
linux
darwin
#+end_src
