#+title: Readme
#+PROPERTY: header-args :tangle .config/mpv/mpv.conf :mkdirp yes

* Table of content :TOC:
- [[#mpv][mpv]]
- [[#mpvconf][mpv.conf]]
- [[#inputconf][input.conf]]
- [[#plugins][plugins]]
  - [[#insalled-plugins][insalled plugins]]
- [[#gnu-stow][Gnu stow]]
- [[#tagging][Tagging]]

* mpv
mpv is a media player based on MPlayer and mplayer2. It supports a wide variety of video file formats, audio and video codecs, and subtitle types. Special input URL types are available to read input from a variety of sources other than disk files. Depending on platform, a variety of different video and audio output methods are supported.

[[https://mpv.io/manual/stable/][document]]
* mpv.conf
:PROPERTIES:
:header-args: :tangle .config/mpv/mpv.conf :mkdirp yes
:END:

[[https://www.reddit.com/r/mpv/comments/opoorx/mpv_with_ytdlp/][replace youtube-dl]] because it's download speed is limited to ~60k/s
#+begin_src conf
script-opts=ytdl_hook-ytdl_path=yt-dlp

ytdl-format=bestvideo[height<=720][ext=webm]+bestaudio/best[height<=720][ext=webm]'
#+end_src

cache
#+begin_src conf
cache=yes
cache-secs=30
demuxer-max-bytes=123400KiB
demuxer-readahead-secs=30

# workaround for streaming video, seek within cache
force-seekable=yes
hr-seek=yes
hr-seek-framedrop=yes
#+end_src

* input.conf
:PROPERTIES:
:header-args: :tangle .config/mpv/input.conf :mkdirp yes
:END:

key bindings, [[https://github.com/mpv-player/mpv/blob/master/etc/input.conf][default]]
#+begin_src conf
## seek
LEFT seek -3
RIGHT seek 3
Shift+Left seek -10
Shift+Right seek 10
Alt+Left seek -30
Alt+Right seek 30
Alt+Shift+Left seek -100
Alt+Shift+Right seek 100

## volume
UP add volume 5
DOWN add volume -5

## playback speed
[ add speed -0.25
] add speed 0.25
{ multiply speed 0.5
} multiply speed 2.0
0 set speed 1.0
#+end_src

* plugins
popular lua scripts can be found at https://nudin.github.io/mpv-script-directory/

** insalled plugins
*** [[https://github.com/jgreco/mpv-youtube-quality][youtube-quality]]

'C-f' to show the available list.

need to modify the source code to change the 'youtube-dl' to 'yt-dlp'

* Gnu stow
#+begin_src pattern :tangle .stow-local-ignore
#+end_src

* Tagging
#+begin_src tag :tangle TAGS
linux
darwin
#+end_src
