#!/usr/bin/env bash
# set -x

# ====== Variables =============================
declare -A gaps
declare -A color

gaps["top"]="0"
gaps["bottom"]="0"
gaps["left"]="0"
gaps["right"]="0"
gaps["inner"]="2"

color["focused"]="0xFF30C730"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"
SPACEBAR_HEIGHT=$(spacebar -m config height)

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         4
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.99
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config window_origin_display       focused
# yabai -m config window_origin_display       cursor

yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="Apple System" app="(System Preferences|System Information|System Settings)" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Digital Color Meter" app="Digital Color Meter" manage=off
yabai -m rule --add label="Guake" app="iTerm2" title="^Guake.*" manage=off grid="20:20:0:15:20:5" sticky=on border=off mouse_follows_focus=off
yabai -m rule --add label="mpv-bundle" app="mpv-bundle" manage=off
yabai -m rule --add label="IINA" app="IINA" manage=off
yabai -m rule --add label="Karabiner" app="^Karabiner-" manage=off
yabai -m rule --add label="UTM" app="UTM" manage=off
yabai -m rule --add label="Vorta" app="Vorta" manage=off
yabai -m rule --add label="Alfred" app="Alfred Preferences" manage=off
yabai -m rule --add label="Preview modal" app="Preview" title="\.(png|jpg|svg)$" manage=off
yabai -m rule --add label="nvALT" app="nvALT" manage=off border=off mouse_follows_focus=off

# ===== Signals ================================
