# light powerlevel10k theme
zinit ice depth"1"
zinit light romkatv/Powerlevel10k

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
zinit ice if'[[ -f "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]]'
zinit snippet "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"

zinit ice if'[[ -f "$ZDOTDIR/.p10k.zsh" ]]'
zinit snippet "$ZDOTDIR/.p10k.zsh"

typeset -g POWERLEVEL9K_TERM_SHELL_INTEGRATION=true
