#+title:  Reademe
#+PROPERTY: header-args :tangle .config/tmux/tmux.conf :mkdirp yes
#+STARTUP: content

* Table of contents :TOC@3:
- [[#tmux][tmux]]
- [[#config][config]]
  - [[#before][before]]
    - [[#packages][packages]]
    - [[#options][options]]
  - [[#after][after]]
    - [[#key-bindings][key-bindings]]
    - [[#the-very-end][the very end]]
- [[#gnu-stow][Gnu stow]]
- [[#tagging][Tagging]]

* tmux
[[https://github.com/tmux/tmux][tmux]] is a terminal multiplexer. It lets you switch easily between several programs in one terminal, detach them (they keep running in the background) and reattach them to a different terminal.
* config
:PROPERTIES:
:header-args: :tangle (org-sbe helper.org.resolve-path (path $"tmux.conf")) :mkdirp yes
:END:

#+NAME: variables
| Variable | Value               | Description           |
|----------+---------------------+-----------------------|
| basedir  | .build/.config/tmux/ | dotfile target folder |

One of the plugin makes truecolor disabled, I had to put the truecolor xterm setting at the very end to override it. TODO, find the plugin.

** before
*** packages
managed by [[https://github.com/tmux-plugins/tpm][TPM]]
#+begin_src conf
# TMUX_PLUGIN_MANAGER_PATH is needed
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'roosta/tmux-fuzzback'
#+end_src

*** options
#+begin_src conf
# don't spawn login shell, becaulse it has been set by terminal emulator.
set -g default-command "$SHELL"
set -g set-clipboard on
set -g mouse on # allowing mouse to select to clipboard and resize pane

# Make switching to cmd mode in zsh quick!
set -g repeat-time 250

## update the TERM variable of terminal emulator when creating a new session or attaching a existing session
set -g update-environment 'DISPLAY \
      SSH_ASKPASS \
      SSH_AGENT_PID \
      SSH_CONNECTION \
      WINDOWID \
      XAUTHORITY \
      TERM'

# status bar positon top
set -g status-position top

# Start pane numbering at 1
set -g base-index 1

# Sane scrolling
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g terminal-overrides '\*:smcup@:rmcup@'

set -g word-separators ' @(){}'

setw -g xterm-keys on

# vi-style controls in copy mode
set -g mode-keys vi

set -g word-separators ' @(){}'
#+end_src
**** themes
***** [[https://draculatheme.com/tmux][dracula theme]]
#+begin_src conf
set -g @plugin 'dracula/tmux'

# powerline symbols, triangle symbol [true / false*]
set -g @dracula-show-powerline false

# window flags [true / false]
# see window-status-format for detail
set -g @dracula-show-flags true

# it can accept `session`, `smiley`*, `window`, or any character.
set -g @dracula-show-left-icon smiley

# high contrast border, [true / false*]
set -g @dracula-border-contrast false

# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, network, network-bandwidth, network-ping, weather, time
set -g @dracula-plugins "cpu-usage ram-usage"

# false* for CPU percentange, true for system load
set -g @dracula-cpu-display-load true
#+end_src

***** nested remote tmux(disabled)
this is old config, haven't migrate to new one, just leave here without tangle.
the idea is to use F12 shift control between local and remote and use different theme to distinguish environments.

#+begin_src conf :tangle no

# when data input speed faster than terminal display rate, instead update everything to screen
# tmux can update screen every interval time. with proper value, can workaround for terminal
# like gnome-terminal and terminator freeze when input data is large.

#setw -g c0-change-trigger 10   # default 250
#setw -g c0-change-interval 250 # default 100

# ==============================================
# ===   Nesting local and remote sessions     ===
# ==============================================

# Session is considered to be remote when we ssh into host
if-shell 'test -n "$SSH_CLIENT"' \
    'source-file ~/.tmux/tmux.remote.conf'

bind -T root F12  \
    set prefix None \;\
    set key-table off \;\
    source-file "${TMUX_PLUGIN_MANAGER_PATH}/tmux-themepack/default.tmuxtheme" \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  source-file "${TMUX_PLUGIN_MANAGER_PATH}/tmux-themepack/powerline/block/orange.tmuxtheme" \;\
  refresh-client -S

#+end_src

** after
*** key-bindings
- global
    | FROM          | DESCRIPTION                              | KEY                    |
    |---------------+------------------------------------------+------------------------|
    |               | alt                                      | M                      |
    |               | prefix                                   | Ctrl - s               |
    |               | copy mode                                | M -️ up                 |
    | tmux-sensible | previous window                          | prefix + C - p         |
    | tmux-sensible | next window                              | prefix + C - + n       |
    |               | choose session                           | prefix + C - + s       |
    |               | rotate panes                             | prefix + C - + o       |
    |               | next layout                              | prefix + C - + p       |
    |               | show clock                               | prefix + C - + 0       |
    |               | paste last yanked text                   | prefix + C - + =       |
    |               | maximize pane                            | prefix + C - + m       |
    |               | command mode                             | prefix - ;             |
    |               | confirm before kill a pane               | prefix - x             |
    |               | reload config                            | prefix - r             |
    | pane-control  | focus pane left                          | prefix + C - h         |
    | pane-control  | focus pane down                          | prefix + C - j         |
    | pane-control  | focus pane up                            | prefix + C - k         |
    | pane-control  | focus pane right                         | prefix + C - l         |
    | pane-control  | resize pane left                         | prefix + shift + C - h |
    | pane-control  | resize pane down                         | prefix + shift + C - j |
    | pane-control  | resize pane up                           | prefix + shift + C - k |
    | pane-control  | resize pane right                        | prefix + shift + C - l |
    | pane-control  | split pane into 2 vertically             | prefix - vbar          |
    | pane-control  | split pane into 2 horizonally            | prefix - hbar          |
    | pane-control  | split pane into 2 vertically full width  | prefix - \             |
    | pane-control  | split pane into 2 vertically full height | prefix - _             |
    | pane-control  | move window left                         | prefix - <             |
    | pane-control  | move window left                         | prefix - >             |
    | tmux-yank     | copy text from command line to clipboard | prefix - y             |
    | tmux-yank     | copy pwd to clipboard                    | prefix - Y             |
    | tmux-thumbs   | copy buffer pattern with hint            | prefix - space         |
    | tmux-fuzzback | fuzzy search buffer                      | prefix - ?             |
    | tpm           | tpm install all packages                 | prefix - I             |
    | tpm           | tpm update all packages                  | prefix - U             |
- Copy mode
    | PS        | DESCRIPTION                     | KEY       |
    |-----------+---------------------------------+-----------|
    | tmux-yank | copy selection to clipboard     | y         |
    | tmux-yank | copy and immediately paste      | Y         |
    | tmux-open | open selected text              | o         |
    | tmux-open | open selected text with $EDITOR | C - o     |
    | tmux-open | google the selected text        | shift - s |
    |           | visual select                   | v         |
#+begin_src conf
# Set the prefix key to Ctrl-z(qwerty) Ctrl-s(dvorak)
set -g prefix C-s

# trigger copy mode by
bind -n M-Up copy-mode

# Ctrl-S: choose session
#bind s choose-session
bind C-S choose-session

# Ctrl-O: Rotate pane
bind o rotate-window

# Ctrl-P: Next layout
bind p next-layout

# Ctrl-D: Detach
bind d detach-client

# Ctrl-0: Clock!
bind 0 clock-mode

# Ctrl-=: choose and past buffer
bind = choose-buffer -F '#{buffer_sample}'

# toggle maximize pane
bind m resize-pane -Z

bind \; command-prompt

bind x confirm-before kill-pane

bind r source-file ~/.config/tmux/tmux.conf

# When scrolling with mouse wheel, reduce number of scrolled rows per tick to "2" (default is 5)
bind -T copy-mode-vi WheelUpPane       select-pane \; send-keys -X -N 2 scroll-up
bind -T copy-mode-vi WheelDownPane     select-pane \; send-keys -X -N 2 scroll-down
bind -T copy-mode-vi v send -X begin-selection
#+end_src
*** the very end
#+begin_src conf

set -g default-terminal "screen-256color"
# tell Tmux that outside terminal supports true color
set -ga terminal-overrides ",xterm-256color*:Tc"

run-shell "$TMUX_PLUGIN_MANAGER_PATH/tpm/tpm"
#+end_src
* Gnu stow
#+begin_src pattern :tangle .stow-local-ignore
#+end_src

Install dotfile
#+begin_src sh :results output
stow -v1 -t ~ .build
#+end_src

#+RESULTS:

Uninstall dotfile
#+begin_src sh :results output
stow -t ~ -D .build
#+end_src

* Tagging
#+begin_src tag :tangle TAGS
linux
darwin
#+end_src
