#!/usr/bin/env bash

function exist {
    ( `hash "$1" 2> /dev/null` ) && return 0 || return 1
}

function run_once {
    pgrep "$@" > /dev/null || ($@ &)
}

# enable transparent
exist compmgr && xcompmgr -cF &
#[ -e  "${HOME}/script/login/firefox-sync" ] && run_once "${HOME}/script/login/firefox-sync"
exist gnome-sound-applet && gnome-sound-applet &
exist nm-applet && nm-applet &
# exist bluetooth-applet && bluetooth-applet &
# keymap
exist keyremap.py && keyremap.py &
# mouse
# run_once 'xset m 3/1 1'

# fix awesome with java program
exist wmname && wmname LG3D &
