#!/usr/bin/env bash

function exist {
    ( `hash "$1" 2> /dev/null` ) && return 0 || return 1
}

function run_once {
    pgrep "$@" > /dev/null || ($@ &)
}

# enable transparent
exist compmgr && run_once 'xcompmgr -cF'
#[ -e  "${HOME}/script/login/firefox-sync" ] && run_once "${HOME}/script/login/firefox-sync"
# exist gnome-sound-applet && run_once 'gnome-sound-applet'
exist nm-applet && run_once 'nm-applet'
# exist bluetooth-applet && bluetooth-applet &
# keymap
exist keyremap.py && run_once 'keyremap.py'
# mouse
# run_once 'xset m 3/1 1'

# fix awesome with java program
exist wmname && run_once 'wmname LG3D'

# at work
if [ `hostname` =  'jchien-4free' ]; then
    # disable notebook screen
    run_once 'xrandr --output LVDS --off'
fi
